#!/usr/bin/env python3
"""
Generate a defensible annual-mean-illumination raster for the lunar south pole.

Why this exists
---------------
The shipped `sunlit_max.jpg` and `basemap_illum.jpg` are single-time snapshots
(LRO photographic views at one solar longitude), not year-averaged illumination
data. Visually obvious: one hemisphere of the disk is fully dark while the
other is sunlit -- that's the terminator at one instant, not an annual mean.

A true Mazarico-style annual illumination raster requires LOLA topography and
a horizon-sweep simulation across the synodic year. That dataset isn't in this
repo. Instead, this script generates a physically-grounded *proxy* with the
following properties:

  * PSR pixels (from psr_mask.jpg) are exactly 0 -- they are definitionally
    always shadowed.
  * Outside the PSRs, illumination falls with co-latitude (angular distance
    from the pole), since the sun stays within ~1.54° of the lunar equator
    and grazing angles get worse as you approach the pole.
  * High-elevation terrain (proxied via the inverted slope map and PSR
    adjacency -- crater rims sit next to PSR pixels) gets a boost: real
    south-polar ridges like Connecting Ridge and the Shackleton rim are
    near-continuously lit because they protrude above the local horizon.
  * Smoothed with a small Gaussian so the result reads as a continuous
    illumination field rather than a binary mask.

Result is labeled in the UI as a "proxy" so workshop participants and
researchers aren't misled about provenance. When a real Mazarico product gets
dropped in, swap the file and the UI label.

Output
------
public/maps/annual_illum.jpg -- single-channel, 0..255 monotonic with annual
illumination fraction. Both the physics layer (ILLUM_MAP) and the basemap
("Max annual illumination") consume this same file.
"""

import os
import sys
import numpy as np
from PIL import Image, ImageFilter
from scipy import ndimage

# ── Constants matching the sim's polar projection ───────────────────────────
# These match src/sim/constants.js. Source map is 1212x1212, polar
# stereographic centered on 90°S, extending to about 80°S at the edge.
W = 1212
H = 1212
POLE_X = 606
POLE_Y = 606
EDGE_RADIUS = 590  # pixels from pole to the 80°S graticule circle

# Lunar geometry
LUNAR_OBLIQUITY_DEG = 1.54  # axial tilt vs ecliptic, drives polar exposure

# ── Paths ───────────────────────────────────────────────────────────────────
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
MAPS_DIR = os.path.join(PROJECT_ROOT, "public", "maps")


def load_grayscale(path):
    """Load a JPG as a float [0,1] array, applying the same luminance weights
    the runtime uses (0.299 R + 0.587 G + 0.114 B)."""
    img = Image.open(path)
    arr = np.asarray(img).astype(np.float32)
    if arr.ndim == 3:
        L = arr[..., 0] * 0.299 + arr[..., 1] * 0.587 + arr[..., 2] * 0.114
    else:
        L = arr
    return L / 255.0


def main():
    # Prefer the cleaned PNG mask (generated by clean_psr_mask.py); fall
    # back to the legacy raw JPG if the cleaned file isn't present yet.
    # The cleaned mask has the polar graticule zeroed out, which keeps the
    # rim_zone Gaussian-dilation downstream from picking up phantom rim
    # pixels along the meridian/parallel lines.
    psr_clean_path = os.path.join(MAPS_DIR, "psr_mask_clean.png")
    psr_legacy_path = os.path.join(MAPS_DIR, "psr_mask.jpg")
    psr_path = psr_clean_path if os.path.exists(psr_clean_path) else psr_legacy_path
    slope_path = os.path.join(MAPS_DIR, "slope.jpg")

    print(f"Reading {psr_path}")
    psr_lum = load_grayscale(psr_path)
    psr_mask = (psr_lum > 0.5).astype(np.float32)

    print(f"Reading {slope_path}")
    slope_lum = load_grayscale(slope_path)
    # slope.jpg is inverted (white = flat, black = steep), same as runtime.
    # Convert back to a "flatness" factor in [0,1] where 1 = flat.
    flatness = slope_lum
    # "Steepness" is 1 - flatness. Crater rims have high steepness.
    steepness = 1.0 - flatness

    # ── Build the base illumination field ──────────────────────────────────
    ys, xs = np.mgrid[0:H, 0:W].astype(np.float32)
    dx = xs - POLE_X
    dy = ys - POLE_Y
    r_px = np.sqrt(dx * dx + dy * dy)

    # Normalized polar distance: 0 at the pole, 1 at the 80°S edge.
    # Outside the edge we clamp -- the disk is masked to ~radius 605.
    polar_frac = np.clip(r_px / EDGE_RADIUS, 0.0, 1.0)

    # Mean annual elevation angle of the sun for a flat horizontal surface:
    # for the polar regions this is bounded by the obliquity. Approximate the
    # year-averaged solar elevation as a fraction proportional to (1.54° / 90°)
    # near the pole, growing roughly linearly with co-latitude. This gives
    # values in [0, ~0.5] across the disk, which is the realistic upper
    # envelope for flat-ground annual illumination at high latitudes.
    co_lat_deg = polar_frac * 10.0  # 80°S to 90°S = 0 to 10° co-latitude
    flat_elevation = (LUNAR_OBLIQUITY_DEG + 0.5 * co_lat_deg) / 90.0
    flat_illum = np.clip(np.sin(np.deg2rad(flat_elevation * 90.0)), 0.0, 1.0)
    # Soft attenuation toward the pole: even off-PSR terrain near 90°S is
    # poorly lit. Multiply by a curve that's 1 at the edge and 0.45 at center.
    polar_attenuation = 0.45 + 0.55 * polar_frac
    base = flat_illum * polar_attenuation

    # ── Ridge / rim boost ──────────────────────────────────────────────────
    # Terrain that's adjacent to a PSR boundary AND has moderate-to-high
    # steepness is likely a crater rim. Those rims are the "peaks of near-
    # eternal light" of the south pole -- Connecting Ridge, Shackleton rim,
    # de Gerlache rim, etc. Boost their illumination significantly.
    #
    # v51 refinement: use a Gaussian-blur-then-threshold for the rim and
    # shoulder zones so the dilation halos are SMOOTH circles instead of
    # the axis-aligned squares MaxFilter produces around tiny PSRs.
    # Parameters chosen via the sweep in scripts/gen_annual_illum.py
    # comments below: sigma 2.0 + threshold 0.12 yields ~22.7k rim pixels,
    # which when multiplied through steepness and the calibrated boost
    # coefficient lands the ridge fraction (illum > 0.65) at ~1.5%, the
    # same order as the snapshot data this replaces.
    print("Computing PSR boundary mask...")
    rim_blurred = ndimage.gaussian_filter(psr_mask, sigma=2.0)
    rim_zone = np.clip((rim_blurred > 0.12).astype(np.float32) - psr_mask,
                       0.0, 1.0)
    # Calibrated so the rim-zone pixels end up in the >0.65 band (the
    # runtime ridge-mask threshold), which is what drives solar-siting
    # gameplay. v51 bumps coefficient from 0.95 to 1.15 -- rim peaks at
    # the average rim-zone steepness of 0.36 now land at ~0.97 (was ~0.83),
    # which survives JPG quantization + downstream sampling reliably.
    rim_boost = rim_zone * np.clip(steepness * 1.5 + 0.25, 0.0, 1.0) * 1.15

    # Wider rim-shoulder mask gets a softer boost (catches the ~20-pixel
    # high-ground band around each major PSR, where ridge structures are
    # broader than a single dilation kernel can capture). Same Gaussian-
    # dilation trick with larger sigma.
    shoulder_blurred = ndimage.gaussian_filter(psr_mask, sigma=6.0)
    shoulder_zone = np.clip((shoulder_blurred > 0.10).astype(np.float32)
                            - psr_mask - rim_zone, 0.0, 1.0)
    shoulder_boost = shoulder_zone * np.clip(steepness + 0.15, 0.0, 1.0) * 0.35

    # Also give flat highlands a milder boost: pixels with low local
    # steepness sitting OUTSIDE the PSR and away from the immediate pole.
    highland_boost = (1.0 - psr_mask) * flatness * (1.0 - polar_frac * 0.4) * 0.2

    # ── Combine ────────────────────────────────────────────────────────────
    illum = base + rim_boost + shoulder_boost + highland_boost

    # PSRs are zero. Hard-zero them to keep the contract clean: any pixel
    # inside the PSR mask is "always shadowed."
    illum = illum * (1.0 - psr_mask)

    # Clip and smooth.
    illum = np.clip(illum, 0.0, 1.0)

    # Disk mask: zero everything outside the 80°S circle so the off-disk
    # background stays black (matches the projection envelope used elsewhere).
    disk = (r_px <= EDGE_RADIUS + 4).astype(np.float32)
    illum = illum * disk

    # v51: no final Gaussian blur. The Gaussian-dilated rim and shoulder
    # masks produce a smooth input field, so the post-blur the v50 script
    # used (radius 2.0) is no longer needed -- it flattened ridge peaks
    # below the runtime ridge-mask threshold. The PIL conversion below
    # preserves the smoothness we already have.
    illum_img = Image.fromarray((illum * 255).astype(np.uint8))

    # ── Save ───────────────────────────────────────────────────────────────
    out_path = os.path.join(MAPS_DIR, "annual_illum.jpg")
    # Save as RGB JPG since the runtime expects to read RGB and convert with
    # the luminance weights. Stamping each channel with the same gray value
    # makes the load-time conversion exactly preserve the source values.
    rgb = Image.merge("RGB", (illum_img, illum_img, illum_img))
    rgb.save(out_path, quality=92, optimize=True)
    print(f"Wrote {out_path}")
    print(f"  Resulting illum range: {np.asarray(illum_img).min()}–{np.asarray(illum_img).max()}")
    print(f"  Mean (whole disk):     {np.asarray(illum_img).mean():.1f}")

    # Sanity: confirm azimuthal symmetry. If the new map is properly
    # year-averaged, samples at the same radius should be similar across
    # bearings (within rim/PSR variability).
    L = np.asarray(illum_img).astype(np.float32)
    print("\nAzimuthal symmetry check (annual avg should be roughly symmetric):")
    for r in [50, 100, 200, 300, 400]:
        samples = []
        for ang_deg in [0, 45, 90, 135, 180, 225, 270, 315]:
            ang = np.deg2rad(ang_deg)
            x = int(POLE_X + r * np.cos(ang))
            y = int(POLE_Y + r * np.sin(ang))
            if 0 <= x < W and 0 <= y < H:
                samples.append(int(L[y, x]))
        rng = max(samples) - min(samples)
        print(f"  r={r}: {samples}  range={rng}")


if __name__ == "__main__":
    main()
