#!/usr/bin/env python3
"""
Generate `basemap_psr_clean.jpg` from clean source data instead of inpainting
the legacy version.

Why this exists
---------------
The shipped `basemap_psr_clean.jpg` had baked-in crater names, graticule
labels, and a legend artifact. `clean_basemap_labels.py` mostly removed them
via inpainting, but the central crater cluster (Shackleton, Faustini, de
Gerlache) has too-varied background terrain for inpainting to fully erase
the labels -- the result has visible ghosting in that region.

This script builds a fresh "topographic with PSRs highlighted" basemap from
two clean source data products that ARE label-free:

  1. `basemap_dramatic_clean.jpg` -- the (also-just-cleaned) shaded-relief
     topo background. Visual style: blue-tinted, dramatic relief.
  2. `psr_mask.jpg` -- the binary PSR mask.

The PSRs are overlaid on the topo background as a soft cyan tint with a
slight inner glow, matching the visual idiom of the previous basemap
(PSRs read as "icy / cold-trap" regions). The result has no baked labels
because neither source has them.

Output
------
public/maps/basemap_psr_clean_clean.jpg -- new clean basemap. Replaces the
inpaint-ghosted version of the same filename produced by
clean_basemap_labels.py. mapData.js consumes this path; no code change
needed. The legacy `basemap_psr_clean.jpg` (with baked labels) stays on
disk for reference.
"""

import os
import numpy as np
from PIL import Image, ImageFilter
from scipy import ndimage

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
MAPS_DIR = os.path.join(PROJECT_ROOT, "public", "maps")

# Tint colour for PSR overlay: a cool cyan that reads as "icy cold trap".
# Matches the legacy basemap_psr_clean aesthetic.
PSR_TINT_RGB = (180, 230, 245)   # light cyan
PSR_TINT_ALPHA = 0.55             # blend strength on PSR pixels
PSR_HALO_ALPHA = 0.18             # soft halo strength on rim pixels


def main():
    topo_path = os.path.join(MAPS_DIR, "basemap_dramatic_clean.jpg")
    # Prefer the cleaned PNG mask (graticule-free, generated by
    # clean_psr_mask.py). Fall back to legacy JPG if the cleaned file
    # isn't present yet. Using the cleaned mask means the cyan halos
    # below won't pick up phantom mid-luminance graticule pixels.
    psr_clean_path = os.path.join(MAPS_DIR, "psr_mask_clean.png")
    psr_legacy_path = os.path.join(MAPS_DIR, "psr_mask.jpg")
    psr_path = psr_clean_path if os.path.exists(psr_clean_path) else psr_legacy_path
    out_path = os.path.join(MAPS_DIR, "basemap_psr_clean_clean.jpg")

    if not os.path.exists(topo_path):
        print(f"Missing {topo_path}. Run clean_basemap_labels.py first.")
        return

    print(f"Reading {topo_path}")
    topo = np.asarray(Image.open(topo_path).convert("RGB")).astype(np.float32)
    H, W, _ = topo.shape

    print(f"Reading {psr_path}")
    psr_img = Image.open(psr_path).convert("L")
    # PSR mask shipped at 1212x1212; topo is 2424x2424. Resize PSR to match.
    if psr_img.size != (W, H):
        psr_img = psr_img.resize((W, H), Image.NEAREST)
    psr_lum = np.asarray(psr_img).astype(np.float32)
    psr_mask = (psr_lum > 128).astype(np.float32)

    # Halo: dilate the PSR mask softly to get a glow zone just outside each
    # PSR. Use Gaussian dilation to match the smooth look of the annual
    # illumination map.
    halo_blurred = ndimage.gaussian_filter(psr_mask, sigma=4.0)
    halo = np.clip(halo_blurred * 1.5, 0.0, 1.0) - psr_mask
    halo = np.clip(halo, 0.0, 1.0)
    # Soften the halo edge for a glow rather than a hard ring.
    halo = ndimage.gaussian_filter(halo, sigma=2.0)

    # Blend: PSR pixels get strong tint. Rim halo pixels get soft tint.
    # The base topo color is preserved underneath.
    tint = np.array(PSR_TINT_RGB, dtype=np.float32)

    psr_blend = psr_mask[..., None] * PSR_TINT_ALPHA
    halo_blend = halo[..., None] * PSR_HALO_ALPHA
    blend = np.clip(psr_blend + halo_blend, 0.0, 1.0)

    # Linear interpolation between topo color and tint color
    out = topo * (1.0 - blend) + tint[None, None, :] * blend
    out = np.clip(out, 0.0, 255.0).astype(np.uint8)

    # Brighten PSRs slightly so they pop out a bit more from the dark
    # topo background (the topo is fairly dark; without a brightness lift
    # PSRs read as the same value, just blue).
    out_img = Image.fromarray(out)

    out_img.save(out_path, quality=92, optimize=True)
    print(f"Wrote {out_path}")
    print(f"  PSR pixels rendered: {int(psr_mask.sum())} / {int(psr_mask.size)} "
          f"({100*psr_mask.sum()/psr_mask.size:.2f}%)")
    print(f"  Halo pixels rendered: {int((halo > 0.05).sum())} "
          f"({100*(halo > 0.05).sum()/halo.size:.2f}%)")


if __name__ == "__main__":
    main()
